copy /Y "..\source\CodinGameTemplate.c" "minimized.c"

cscript replace.vbs "minimized.c" " = " "="
cscript replace.vbs "minimized.c" " < " "<"
cscript replace.vbs "minimized.c" " == " "=="
cscript replace.vbs "minimized.c" " > " ">"
cscript replace.vbs "minimized.c" " != " "!="
cscript replace.vbs "minimized.c" " + " "+"
cscript replace.vbs "minimized.c" " * " "*"
cscript replace.vbs "minimized.c" " - " "-"
cscript replace.vbs "minimized.c" "; " ";"
cscript replace.vbs "minimized.c" ", " ","
cscript replace.vbs "minimized.c" " += " "+="
cscript replace.vbs "minimized.c" " *= " "*="
cscript replace.vbs "minimized.c" " -= " "-="
cscript replace.vbs "minimized.c" " && " "&&"
cscript replace.vbs "minimized.c" " || " "||"
cscript replace.vbs "minimized.c" "for (" "for("
cscript replace.vbs "minimized.c" ") {" "){"
cscript replace.vbs "minimized.c" "if (" "if("
cscript replace.vbs "minimized.c" ") {" ") {"
cscript replace.vbs "minimized.c" "} else {" "}else{"
cscript replace.vbs "minimized.c" "else {" "else{"
